### ISSUE TITLE
How to change 'Links' and other URLs in the footer?

### ISSUE THREAD

**Issue by Hoggie** [tpeigne/simpleresponsivetheme#10]
I can see 'Links' in the footer, but cannot find where I can change the default URL (/#) for 'Links' and other lines in the footer.

Any advise?

Thank you.

**Comment by tpeigne** [comment]
Hello, you can have a look here : https://github.com/tpeigne/simpleresponsivetheme/blob/master/modules/responsivelinks/views/templates/hook/responsivelinksfooter.tpl
