### ISSUE TITLE
Currency Choice block disappeared

### ISSUE THREAD

**Issue by Hoggie** [tpeigne/simpleresponsivetheme#11]
Not sure when exactly it happend. Maybe after you fixed this issue:
https://github.com/tpeigne/simpleresponsivetheme/issues/6

Please check.

Thank you in advance

**Comment by tpeigne** [comment]
Hello Hoggie,

The block currency isn't compatible with my theme, sorry :(

**Comment by Hoggie** [comment]
It's quite disappointing... 
This way your theme will be useful only to local shops.

Any plans to connect this module to your theme? 

Thanks again for the great job you make.
