### ISSUE TITLE
Responsive Slider: Property ResponsiveSliderClass->url is not valid

### ISSUE THREAD

**Issue by spidou** [tpeigne/simpleresponsivetheme#13]
Hi,
I'm trying to add a new slider, but when I give an URL (relative or absolute) and submit the form, it raises an exception (see attached screenshot).
![responsive slider exception](https://f.cloud.github.com/assets/59434/1031471/393932a4-0ee1-11e3-8512-7240c4c84115.png)

Can you tell me if the given URL must be respect a specific pattern, or something?

It would be great if we could choose a target like you did on Responsive Links (link to existing category, CMS page, Product page, etc)

**Comment by tpeigne** [comment]
Hello spidou and thanks for your report.

What was you url ? And what is the version module ?

I've planned to add target link like you said in the next version of the module !

**Comment by spidou** [comment]
The URL was a link to a product of my store : "http://localhost/prestashop/index.php?id_product=8&controller=product"

I also tried with "prestashop/index.php?id_product=8&controller=product" and "index.php?id_product=8&controller=product", but got the same error.

I use the version 2.2 of Responsive Slider.

**Comment by tpeigne** [comment]
Hello spidou !

I caught the problem ! I've created a validation that use the PS validation system for the url but choose the isGenericName function for validating the field instead of isUrl. 

And your problem is that in the string, the character "=" is not allowed. See the PrestaShop function : 

```
public static function isGenericName($name)
{
    return empty($name) || preg_match('/^[^<>=#{}]*$/u', $name);
}
```

And the right function : 

```
public static function isUrl($url)
{
    return preg_match('/^[~:#,%&_=\(\)\.\? \+\-@\/a-zA-Z0-9]+$/', $url);
}
```

**Comment by spidou** [comment]
Perfect! Thanks ;)
