### ISSUE TITLE
Long category descriptions will cause duplication of description in front office

### ISSUE THREAD

**Issue by Hoggie** [tpeigne/simpleresponsivetheme#18]
I suspect that it's not about simpleresponsivetheme, but about PrestaShop, but anyway:

If we make long category description (long enough to show 'Plus....' link , CMS cannot show it correctly. The description will be duplicated as shown on the screenshot (there is only 1 line in the description, but it shows 3.

![screen](https://f.cloud.github.com/assets/5220642/1069814/3647ad88-1430-11e3-8279-4b988b8ccab5.png)

**Comment by tpeigne** [comment]
Hello,

Feel free to commit a patch for this, it will be great !

Thanks
