### ISSUE TITLE
Site off

### ISSUE THREAD

**Issue by Amial** [tpeigne/simpleresponsivetheme#2]
hello, and thaks for your template.

your template was working well, but when i put the images of mobile/favicon etc.. the front office dont work....
you can welp me?

my website atela.pt

**Comment by tpeigne** [comment]
Hello Amial,

I provide help only for issues on my theme. You issue don't come with my theme but with a server error (error 500).

I you want some help, you can ask questions on the PrestaShop official forum : [prestashop.com/forums](http://www.prestashop.com/forums/).
