### ISSUE TITLE
'On sale!' not displayed on product list when check box 'Display the "on sale" icon' is checked

### ISSUE THREAD

**Issue by Hoggie** [tpeigne/simpleresponsivetheme#22]
Admin panel:

CHECK BOX [Display the "on sale" icon on the product page, and in the text found within the product listing] is CHECKED

But no 'On sale' tip is displayed in the product list.

However, deafault theme does.

Please see the screenshots showing the HTML pages of Default and SimpleResponsive themes

![screenshot_not_showing_on_sale](https://f.cloud.github.com/assets/5220642/1102311/f7d55bf2-180f-11e3-8f50-63681a5e7db7.png)

**Comment by tpeigne** [comment]
Hello,

This issue will be fixed in the next patch.

Thanks

**Comment by Hoggie** [comment]
As I see, there is some fix already done. I tested it, and it does not work correctly.

Highlighted products are being shown this way:
![action_product](https://f.cloud.github.com/assets/5220642/1142021/b4e207f8-1cc1-11e3-8f33-b20043f717dd.png)

Or you still working on it?

**Comment by edarioq** [comment]
Any update on this issue?
