### ISSUE TITLE
'Notify me when available' while pruduct is in stock (for logged in buyers only) when Stock Management is ON

### ISSUE THREAD

**Issue by Hoggie** [tpeigne/simpleresponsivetheme#23]
Mail alerts module: ON
Stock management or Advanced Stock management: ON
Quantity of product is: >0
Customer logged on.

BUG:
'Notify me when available' link, and it's wrong behaviour.

This bug also presents in the default theme, and Presta team still did not fix it. Let's be better than them. If it's some small bug in product.tpl - I'm sure that it's not hard to find and kill it.

Summary: please see the table.

![notify_me_behavior](https://f.cloud.github.com/assets/5220642/1104143/3fea1140-18e6-11e3-8cd4-1f7868d46db0.png)

**Comment by tpeigne** [comment]
Hello,

If it's a Prestashop issue, please don't open a issue here, if you want to commit a patch for the theme you'r welcome.

Thanks
