### ISSUE TITLE
Switching to mobile view under IE8 - is it normal?

### ISSUE THREAD

**Issue by Hoggie** [tpeigne/simpleresponsivetheme#24]
When opening a site with IE8, it is switching to mobile view.
Is it normal behaviour?
What are minimum requirements for the theme to show the normal view?

Thanks.

**Comment by tpeigne** [comment]
No it's not. 

There are some drawbacks for the responsivetheme on IE8 because it use advanced CSS3 selectors. But your bug on switching to mobile theme don't come with my theme, i think it's a PS issue.

Thanks
