### ISSUE TITLE
'Sad' emoticon in the cart image even when the cart is not empty already

### ISSUE THREAD

**Issue by Hoggie** [tpeigne/simpleresponsivetheme#27]
Empty cart: sad emoticon
Non-empty cart: still sad emoticon

**Comment by tpeigne** [comment]
What is your sad emoticon ? Can you show me a screen shot ?

Thanks !
tpeigne

**Comment by Hoggie** [comment]
![shopping_cart_sad_emoticon](https://f.cloud.github.com/assets/5220642/1261886/2a054d64-2c36-11e3-9e44-a89f3f6d8e2c.png)

Here you are :)

Please see the screenshot of the cart

Have a nice day!

**Comment by tpeigne** [comment]
Ok i see now !

In fact, it's not a sad icon, it's just the poor quality of the cart icon.

Don't have time to change that sorry :(

Thanks,
tpeigne

**Comment by Hoggie** [comment]
Will you please tell the cart image name and path? Thanks!
PS found it.
