### ISSUE TITLE
Pop-up descriptions of the categories contain '<p>' and '</p>'

### ISSUE THREAD

**Issue by Hoggie** [tpeigne/simpleresponsivetheme#28]
Presta 1.5.5
Edit some category description. Save it.
Point mouse cursor to some category name. It begins with 'p' and ends with '/p'

**Comment by tpeigne** [comment]
Hello Hoggie,

On which page did this issue occured ? Have you an example ?

Thanks,
tpeigne

**Comment by Hoggie** [comment]
It occures on every page

Step-by-step guide how to reproduce the bug:

Edit some category description. Make it 10 words or longer (not sure it matters, but just in case)
Save the category.
Point mouse cursor to this category in left column. Pop-up description will start with P and end with /P

Cheers!

**Comment by Hoggie** [comment]
Works indeed. Thanks!
