### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by Amial** [tpeigne/simpleresponsivetheme#3]
hello, tpeigne tkanks for all

now i add a category, but this dont is show on frontoffice 

www.atela.pt

can you say me why?

**Comment by tpeigne** [comment]
Hello,

Displaying or not categories don't come with my theme but with your PrestaShop configuration.

For more help with PrestaShop categories configuration, you can visit PrestaShop official documentation here : http://doc.prestashop.com/display/PS15/Adding+Products+and+Product+Categories#AddingProductsandProductCategories-CreatingaCategory

Thanks,
tpeigne
