### ISSUE TITLE
Footer links not editable?

### ISSUE THREAD

**Issue by colcoops** [tpeigne/simpleresponsivetheme#30]
Can you please check the share module as the link list under:

'Browse column'

and 

'Site Info Column'

Can't be edited from my end anyways.

**Comment by tpeigne** [comment]
Hello colcoops,

What is your issue exactly ? Where did your try to edit these links ?

Thanks,
tpeigne

**Comment by colcoops** [comment]
Hi Thomas

I tried the edit in the admin area under modules

Thanks

Col

**Comment by tpeigne** [comment]
Please give more informations. Which module, which link ?...

**Comment by colcoops** [comment]
I have sent message with login details to your direct email :)

**Comment by colcoops** [comment]
Havent heard from you so I am assuming you didn't get my email.  Please refer to the section which cannot be edited (I am trying to edit them inside the 'responsive links' module).  Some insight into how to edit these links would be great.
Thanks awesome simple theme though.

Col
![capture1](https://f.cloud.github.com/assets/5600734/1322863/28c5f8f8-3452-11e3-8083-1fbcc4b964be.JPG)

**Comment by tpeigne** [comment]
Did you try to add a link ?

**Comment by colcoops** [comment]
yes

**Comment by tpeigne** [comment]
Is the multishop enable ?

**Comment by colcoops** [comment]
Sorry for the hassle...and I really appreciate your help...silly me...finally worked out where to modify footer links in the responsive links module.

Again..thanks....Thomas....Great theme:)
