### ISSUE TITLE
RE: Cannot edit/change file permission for most of the files.

### ISSUE THREAD

**Issue by carpalwatch** [tpeigne/simpleresponsivetheme#31]
Hi,

I need to edit the global.css file in your theme but I kept getting permission denied error and when I tried to change the file permission, it said operation not permitted.

**Comment by tpeigne** [comment]
Hello,

This issue is not related to the simpleresponsivetheme. If you can't edit the global.css file, configure your IDE or change the chmod on the file.

Thanks,
tpeigne
