### ISSUE TITLE
HTML5 validation

### ISSUE THREAD

**Issue by ghost** [tpeigne/simpleresponsivetheme#32]
There are a couple of html5 validation issues that I end up fixing each time I use your module, so would be better if you fixed the source code:
- A </ul> tag that needs shifting up above the div in the responsivetopbar.tpl
- The <section id="sidebar "role="contemporary"> in the footer is invalid. Change this to an aside is a better practice.

Anyway nice simple theme so thanks.

**Comment by tpeigne** [comment]
Can you add more details on this point ? Can you show me the source code of your issue ?

**Comment by JeyjooMilano** [comment]
Hi.
Looking at my message above, I think the original tags and code I put in have been stripped out or interpreted as real html.
I dont have the original problem as I fixed it on my site. But if you use w3c html validator on a website with the theme, you will see the issues. The html errors don't actually cause any visual problem, I just like to have all my websites valid.
Like I said above, changing the section tag in the sidebar into a aside tag will resolve on issue.
The second issue is resolved by moving the ul tag a little further up the code in the responsivetopbar.tpl

**Comment by tpeigne** [comment]
Some W3C errors have been fixed in a5eb05cfe09bbcbab21b10a9c730fc1cbe44c18e, for links errors with the "&" tag, it's a Prestashop error, and i can do nothing for that..
