### ISSUE TITLE
W3C validation error

### ISSUE THREAD

**Issue by hpiontek** [tpeigne/simpleresponsivetheme#37]
Hi Tpeigne,

When running my site with V1.3.1 of this theme through the W3C validator it shows this error: 
Line 11, Column 5985: Bad value complementary for attribute role on element section.
…tion id="sidebar" role="complementary">

Looks like an HTML 5 issue.

Hope this can be fixed.

**Comment by tpeigne** [comment]
According to this doc : http://www.whatwg.org/specs/web-apps/current-work/multipage/elements.html#wai-aria. We have to change the section tag to the aside tag.

I will fix that as soon as possible.

Thanks

**Comment by hpiontek** [comment]
No problem, YW!
