### ISSUE TITLE
Top menu does not show subcategories

### ISSUE THREAD

**Issue by herkyl** [tpeigne/simpleresponsivetheme#4]
When I add a subcategory to one of the top ones the top menu does not show it. Also, how can I remove the menu from showing products all together. If I have 100 different products it list's all, but I only need to show the category of each product.

**Comment by herkyl** [comment]
Figured this out, you had to use the Responsive links block module.

**Comment by tpeigne** [comment]
Ok, nice.

For the moment, all products are listed in a select box. I agree that it's a bad practice if you have a lot of products.

In future updates, i must implement a autocomplete input with an ajax request to search the products.
If you want to develop this feature you're welcome ! 

tpeigne
