### ISSUE TITLE
Language bar is always on

### ISSUE THREAD

**Issue by Hoggie** [tpeigne/simpleresponsivetheme#6]
No possibility to remove the language bar.
If only 1 language is being used in frontoffice, it becomes an indicator of the only one language.

**Comment by tpeigne** [comment]
Good point for you !

I will make a fix later to hide the languages selection if there is only one language.
tpeigne

**Comment by Hoggie** [comment]
Great! Thank you. Waiting... :)

**Comment by Hoggie** [comment]
Works. Thank you!
