### ISSUE TITLE
No translation for 'Home' and 'Contact' links?

### ISSUE THREAD

**Issue by Hoggie** [tpeigne/simpleresponsivetheme#7]
After chanding the language in front office: 'Home' and 'Contact' links are empty, cannot find where the translations for them (if any).

![categories](https://f.cloud.github.com/assets/5220642/953799/fc53897e-0400-11e3-97f5-7472fc759ed6.png)

Any ideas? Thank you.

**Comment by tpeigne** [comment]
All the links in the nav bar are translatable in the responsivlelinks configuration page.

When you install the module for the first time, links are generated automatically for en, br, de, es, fr and it languages. I think that your language isn't in this list so the translation is missing.

You only have to edit the link and it will be ok !
tpeigne

**Comment by Hoggie** [comment]
Exactly. Solved! thank you.

**Comment by gionattan** [comment]
I`m sorry but what do you mean by "edit the link" ?

**Comment by Hoggie** [comment]
Please re-read 1st message

**Comment by gionattan** [comment]
I got it,thanks . And sorry again :)
