### ISSUE TITLE
How to see the version number installed? How to upgrade the current version correctly?

### ISSUE THREAD

**Issue by Hoggie** [tpeigne/simpleresponsivetheme#9]
Q:
How to check the current version No in the site admin panel?

Q: What is the correct way to upgrade the version?
Just install via 'add the theme' module? Will it impact the current translations then?

Thank you in advance.

**Comment by tpeigne** [comment]
Q: the version of the theme ?

Q: update the theme via the theme installer.

**Comment by Hoggie** [comment]
Yes, need to see version of theme. My current is 1.2.0.

**Comment by tpeigne** [comment]
I will update the responsiveextension as soon as possible and add the version of the theme.
